name: api_rest1
description: Um novo projeto flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  mobx: ^1.2.0
  intl: 0.16.1
  flutter_modular: ^1.2.0
  bottom_navy_bar: 5.4.0
  http: 0.12.1
  flutter_svg: 0.17.4

  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/icon1.svg
    - lib/app/assets/icon2.svg
    - lib/app/assets/icon3.svg
    - lib/app/assets/state.png
    - lib/app/assets/coronavirus1.png
    - lib/app/assets/coronavirus2.png
    - lib/app/assets/background.png
    - lib/app/assets/death.png
    - lib/app/assets/medical.png
    - lib/app/assets/virus.png
    - lib/app/assets/health.png
    - lib/app/assets/time.png
